config/routes.rb
Rails.application.routes.draw do
  resources :guesses
  devise_for :users
  resources :words
  resources :puzzles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "puzzles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guess.rb
# == Schema Information
#
# Table name: guesses
#
#  id          :integer          not null, primary key
#  correct     :boolean          default(FALSE)
#  input_guess :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#  word_id     :integer          not null
#
# Indexes
#
#  index_guesses_on_user_id  (user_id)
#  index_guesses_on_word_id  (word_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#  word_id  (word_id => words.id)
#
class Guess < ApplicationRecord
  belongs_to :user
  belongs_to :word

  def correct?
    input_guess.upcase == word.name.upcase
  end

  def check_letters
    guess_letters = input_guess.upcase.split("")
    word_letters = word.name.upcase.split("")
    letter_classes = []
    guess_letters.each_with_index do |letter, index|
      if letter == word_letters[index]
        letter_classes << "correct"
      elsif word_letters.include?(letter)
        letter_classes << "misplaced"
      else
        letter_classes << "wrong"
      end
    end
  letter_classes
  end

  def prettify
    html_string = ""
    guess_letters = input_guess.downcase.split("")
    letter_classes = check_letters
    guess_letters.each_with_index do |letter, ind|
      html_string.concat("<span class='", letter_classes[ind], "'>", letter, "</span>")
    end
    html_string.html_safe
  end
end

app/models/puzzle.rb
# == Schema Information
#
# Table name: puzzles
#
#  id               :integer          not null, primary key
#  publication_date :date
#  author           :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Puzzle < ApplicationRecord
    has_many :words
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id         :integer          not null, primary key
#  name       :string
#  order      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  puzzle_id  :integer
#
# Indexes
#
#  index_words_on_puzzle_id  (puzzle_id)
#
class Word < ApplicationRecord
    belongs_to :puzzle
    has_many :guesses

        def guessed?
        guesses.find_by(correct: true).present?
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  # POST /guesses or /guesses.json
  def create
    @guess = Guess.create(guess_params)
    if @guess.correct?
      @guess.update(correct: true)
      redirect_to @guess.word.puzzle, notice: "GOT IT"
    else
      redirect_to @guess.word, notice: "Try again"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess
      @guess = Guess.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guess_params
      params.require(:guess).permit(:user_id, :word_id, :input_guess)
    end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :set_puzzle, only: %i[ show  ]
  before_action :authenticate_user!

  # GET /puzzles or /puzzles.json
  def index
    @puzzle = Puzzle.find_by(publication_date: Date.today)
  end

  # GET /puzzles/1 or /puzzles/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzle
      @puzzle = Puzzle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def puzzle_params
      params.require(:puzzle).permit(:publication_date, :author)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_word, only: %i[ show ]

  # GET /words/1 or /words/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:name, :order)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def stop_words
        [ "a", "the", "and", "in", "as", "it", "my", "not", "you,", "do", "we", "see", "it's", "but" ]
    end
end

app/views/guesses/_form.html.erb
<%= form_with(model: @word.guesses.new) do |f| %>
  <%=f.hidden_field :user_id, value: current_user&.id  %> 
  <%=f.hidden_field :word_id, value: @word.id  %> 

<%=f.hidden_field :word_id,value:@word.id %> 

<br><br><br><br>
<br><br><br><br>

<div data-controller="quotle">
<div class="letters"> 
 <% @word.name.split('')&.each_with_index do |letter, index| %>
  <%=f.text_field :letter, maxlength: 1, 'data-quotle-target'=>'input' ,"data-action"=>"quotle#autoAdvance" %>
  <% end %>
  <%=f.hidden_field :input_guess, 'data-quotle-target'=>'output'  %> 
</div>
    <%= f.submit value="Guess", 'data-action'=>'click->quotle#transferWord' %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="site-title">
    <%=link_to "Quotle", root_path %>
  </div>
  <div class="author">
    <%=link_to "Calvin Murphy", "https://calvin.josephmurphy.name/" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title><%= content_for(:title) || "Quotle" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/header" %>
   <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %> 
  </body>
</html>

app/views/puzzles/_about.html.erb
<h2>About Quotle</h2>
<p>Quotle is like Wordle but you guess each of the words in a famous quote. Unlike Wordle, with Quotle the words can be any length, and you can have as many guesses as you like. After each guess, you will be able to see if a letter is <span class="correct">c</span><span class="correct">o</span><span class="correct">r</span><span class="correct">r</span><span class="correct">e</span><span class="correct">c</span><span class="correct">t</span>, <span class="misplaced">m</span><span class="misplaced">i</span><span class="misplaced">s</span><span class="misplaced">p</span><span class="misplaced">l</span><span class="misplaced">a</span><span class="misplaced">c</span><span class="misplaced">e</span><span class="misplaced">d</span>, or <span class="wrong">w</span><span class="wrong">r</span><span class="wrong">o</span><span class="wrong">n</span><span class="wrong">g</span>.</p>
<p>Quotle was built by Calvin Murphy using Ruby on Rails and a Postgres database. Authentication is done with the Devise gem. I used Cascading Stylesheets to make the site's appearance, and Javascript for the guessing form. Code available on <%= link_to "Github", "https://github.com/Jafea-gif/quotle/", class: "important" %></p>
 

app/views/puzzles/_puzzle.html.erb
<div id="<%= dom_id puzzle %>">


<div id="words">
  <% @puzzle.words.order(:order).each do |word|
    if word.guessed? || stop_words.include?(word) %>
    <%= word.name %>
    <%else%> 
    <%=link_to "Guess", word, class: 'guess_button' %>
    <%end
  end %>
</div>

  <p>
    <strong>Author:</strong>
    <%= puzzle.author %>
  </p>

</div>

app/views/puzzles/index.html.erb
<% content_for :title, "Puzzles" %>

<main>
<h1>Today's Puzzle</h1>

<div id="puzzles">
    <%= render @puzzle %>
</div>
</main>
<footer>
  <%= render "puzzles/about" %>
</footer>

app/views/puzzles/show.html.erb
<%= render @puzzle %>

app/views/words/show.html.erb
<div id="guesses">
  <% @word.guesses.where(user_id: current_user.id).order(:created_at).each do |guess| %>
    <div>
      <%= guess.prettify %>
    </div>
  <% end %>
  <% unless @word.guessed? %>
    <%= render 'guesses/form', word: @word %>
  <% end %>
  <%= link_to "Back", puzzles_path %>
</div>